### ISSUE TITLE
Add DocSearch Support

### ISSUE THREAD

**Issue by kidonng** [v2fly/v2fly-github-io#15]
Website: https://docsearch.algolia.com/
VuePress docs: https://vuepress.vuejs.org/theme/default-theme-config.html#algolia-search

**Comment by kslr** [comment]
Is the search bad now?

**Comment by kidonng** [comment]
> Is the search bad now?

Not bad, but DocSearch may provide a better experience because it indexes the full documentation, so you can search for more specific items like `alterId`.

**Comment by kslr** [comment]
Ok i have applied

**Comment by kslr** [comment]
https://github.com/v2fly/v2fly-github-io/commit/c135ef7ab10930fc660909d2123b102989b4b246
