### ISSUE TITLE
I have the next problem Main: config file not readable > open /root/config.json

### ISSUE THREAD

**Issue by matiasiutu** [v2fly/v2fly-github-io#181]
when starting the v2ray command with root from it I get this I have ubuntu 18.4

V2Ray v2.37 (One for all) 20170907                                                     An unified platform for anti-censorship.                                               Main: config file not readable > open /root/config.json: no such file or directory

Help meeee !!! Pleaseeee

**Comment by Loyalsoldier** [comment]
Grant V2Ray read and execute permission to the config file and directory. BTW, please upgrade your V2Ray to the latest.
