### ISSUE TITLE
VMess协议的FNV端序没有描述清楚

### ISSUE THREAD

**Issue by huoyaoyuan** [v2fly/v2fly-github-io#197]
https://www.v2fly.org/developer/protocols/vmess.html

> 校验 F：指令部分除 F 外所有内容的 FNV1a hash；

按照定义，FNV算法给出的是一个整数，而非字节序列。为严谨起见，应注明使用了Big-Endian。

**Comment by xiaokangwang** [comment]
Added to TODO. https://github.com/v2fly/v2ray-core/projects/1#card-62053796

**Comment by xiaokangwang** [comment]
Fixed in 454423a820d7022e29d41beb6859c05d97080bac .
