### ISSUE TITLE
是否应该注明工具的开源、闭源状态？

### ISSUE THREAD

**Issue by CrazyBoyFeng** [v2fly/v2fly-github-io#206]
有一些 GUI 客户端以前是开源的，但是后来闭源了。  
我不评价这个行为，只是认为需要一定程度上保障用户的知情权，避免发生误会。  
对一些人来说，这也事关“安全”。

**Comment by kslr** [comment]
闭源/商业 不能出现在推荐列表

**Comment by CrazyBoyFeng** [comment]
以前开源，现在转为闭源的有：
* v2rayNG 👉 2dust/v2rayNG#1047
* [V2rayU](https://github.com/yanue/V2rayU)

**Comment by kslr** [comment]
Thanks for your report. https://github.com/v2fly/v2fly-github-io/commit/12c891d2b17b0300d2ad01b4bfae396f84f2a773
