### ISSUE TITLE
Fail to generate href tags

### ISSUE THREAD

**Issue by Loyalsoldier** [v2fly/v2fly-github-io#3]
The href tags in here are generated failed: https://www.v2fly.org/chapter_02/env.html

And also failed in the same page: https://www.v2fly.org/chapter_02/03_routing.html

![image](https://user-images.githubusercontent.com/10487845/88823536-c7f3ea80-d1f7-11ea-8536-0c16da65b5f8.png)

**Comment by kslr** [comment]
https://vuepress.vuejs.org/zh/guide/markdown.html#%E9%93%BE%E6%8E%A5

**Comment by Loyalsoldier** [comment]
Fix in https://github.com/v2fly/v2fly-github-io/pull/4
