### ISSUE TITLE
The path in the documentation is wrong.

### ISSUE THREAD

**Issue by YouXam** [v2fly/v2fly-github-io#332]
https://github.com/v2fly/v2fly-github-io/blob/master/docs/en_US/developer/intro/compile.md?plain=1#L32

[The Git repository](https://github.com/v2fly/v2ray-core) does not have this path: /infra/control/main

**Comment by KatyushaScarlet** [comment]
Same problem here.
It's seem that there is no "/infra/control/main" directory.

**Comment by KatyushaScarlet** [comment]
#351
