### ISSUE TITLE
The path in the compilation documentation may be wrong

### ISSUE THREAD

**Issue by KatyushaScarlet** [v2fly/v2fly-github-io#351]
https://github.com/v2fly/v2fly-github-io/blob/master/docs/en_US/developer/intro/compile.md?plain=1#L32

It's seem that there is no "/infra/control/main" directory in the [v2ray-core](https://github.com/v2fly/v2ray-core/tree/master/infra) repo.

**Comment by KatyushaScarlet** [comment]
#https://github.com/v2fly/v2ray-core/pull/488

The v2ctl doesn't exist anymore.

**Comment by kslr** [comment]
fixed https://github.com/v2fly/v2fly-github-io/commit/9016804dd92fdd75f9ba71cf9343b7293aec6d52
