### ISSUE TITLE
Can't navigate to routing page.

### ISSUE THREAD

**Issue by kvii** [v2fly/v2fly-github-io#360]
v4 英文版 配置文档的 routing 部分不可访问。但中文版本可以。
文档地址 https://www.v2fly.org/en_US/config/routing.html
<img width="935" alt="截屏2022-12-09 15 21 57" src="https://user-images.githubusercontent.com/56432636/206650136-739fae54-a276-4ed7-b43c-57617800292a.png">

**Comment by puzzle9** [comment]
要不研究下 改个地址 提个pr？

**Comment by kvii** [comment]
@puzzle9 我翻了所有的提交记录，发现这好像不是改个地址就行了的问题。

文档应该是从 20 年 10 月的提交[b537175af11f58d013adc385351c4b925fba174b](https://github.com/v2fly/v2fly-github-io/commit/b537175af11f58d013adc385351c4b925fba174b)开始变成现在 v4 版本的模样的。

然后在 pr #67 左右有了现在的 v4 版配置部分的英文文档。

之后我就基本没有见到 en_us 部分的文档有更新了。所以我推测当时应该就是没写完，没有这部分文档。

还有一个坑爹的地方就是现在的 vuepress 正在从 webpack 往 vite 转型，当前还是 beta 版本。当前的代码直接跑的话跑不起来。我把 docsearchPlugin 注释掉了才跑起来的。

**Comment by puzzle9** [comment]
跑不起来那个因为是 https://github.com/v2fly/v2fly-github-io/pull/368 这个问题

我刚才看了下文档 好像很多入口页面是找不到的 任务量巨大啊

**Comment by kvii** [comment]
@puzzle9 我问了下这个项目的 contributor。这个项目的翻译工作先在是在一个叫 [transifex](https://explore.transifex.com/v2fly/) 的平台上去做的。我顺便查了下现在的 v4 routing 部分的文档。发现确实是没有翻译。
如果您有贡献译文的意愿的话，可以去那个平台。
我稍后会创建新的 issue，建议 v2fly 把这部分信息写进 README 里。避免别人找不到参与贡献的方法。

**Comment by puzzle9** [comment]
@kvii 完了 设计到知识盲区了
v5的文档我看是有 路由 这部分的
那就是相当 他们在 transifex 上把这个些翻译文件直接整成 markdown 然后再提交到仓库是吧

**Comment by kvii** [comment]
@puzzle9 这些问题建议加入[官方电报群](https://www.v2fly.org/guide/help.html#telegram-讨论组-新闻频道)交流呢。
