### ISSUE TITLE
[XTLS]

### ISSUE THREAD

**Issue by ghost** [v2fly/v2fly-github-io#37]
https://github.com/v2fly/v2fly-github-io/commit/db182c744040ca2cf93cd5ec0c75907ae618bb20

` UDP/443 的请求`改为`443端口的UDP请求`会好一些
@rprx

**Comment by RPRX** [comment]
这里用 UDP/443 比较准确，因为是先有 UDP 后有 443。

**Comment by ghost** [comment]
我只是觉得这个文档是面向消费者的，不是开发者的，简单易懂一些比较好/笑哭
@rprx
