### ISSUE TITLE
建议在 README 或官网中写一下现在使用的翻译管理平台的信息

### ISSUE THREAD

**Issue by kvii** [v2fly/v2fly-github-io#373]
据我了解，现在项目使用的了翻译管理平台 [transifex](https://explore.transifex.com/v2fly/)。这个平台可以提供中英文对照之类的功能。
那么是不是可以将这部分介绍写进 README 或官网文档里，介绍给想要贡献翻译的所有用户呢？

**Comment by nicholascw** [comment]
fixed by 53725c200ee1fb73c208d3bb93d3ad88ae93f60e
