### ISSUE TITLE
Does "awesome tools" accept "not free" app?

### ISSUE THREAD

**Issue by ghost** [v2fly/v2fly-github-io#378]
I have made an app which focusses on V5 core, and only supports Apple platform, like macOS and iOS.
The price is free. The free functions contain most necessary features, like router and subscription.  But it also offer some vip features, like cleaning configs and predefining templates.
I think it will be useful for v2ray users.
The macOS version has passed Apple Review and be available on Mac App Store. Here is the link of [Wings V Client](https://apps.apple.com/us/app/wings-v-client/id1659637036).

I'm not sure that wether your team accpets "not free" application, because I won't open source of the app.

If it can be accepted, I'll open a PR to submit it.
If not, please just close this issue.

Sorry for boring you.

**Comment by kslr** [comment]
only accept open source client.
