### ISSUE TITLE
[VLESS][fallbacks]数组元素的排列顺序对配置有没有影响

### ISSUE THREAD

**Issue by ghost** [v2fly/v2fly-github-io#38]
fallbakcs数组元素的排列顺序对配置有没有影响，文档中没有说清楚

**Comment by RPRX** [comment]
若有精确冲突，则后面的会覆盖前面的。

**Comment by RPRX** [comment]
（没有写是因为觉得应该不会有人配置出精确冲突的，即 alpn 和 path 都相同）

**Comment by ghost** [comment]
> （没有写是因为觉得应该不会有人配置出精确冲突的，即 alpn 和 path 都相同）

好

**Comment by RPRX** [comment]
匹配是匹配到最精确的那个，与排列顺序无关。

**Comment by RPRX** [comment]
https://github.com/v2fly/v2fly-github-io/commit/becfb4c11e4432cc97ad3b63efcf2cfa40ece413
