### ISSUE TITLE
[Transport][TLSObject]

### ISSUE THREAD

**Issue by ghost** [v2fly/v2fly-github-io#39]
```
disableSystemRoot: true | false

（V2Ray 4.18+）是否禁用操作系统自带的 CA 证书。默认值为 false。当值为 true 时，V2Ray 只会使用 certificates 中指定的证书进行 TLS 握手。当值为 false 时，V2Ray 只会使用操作系统自带的 CA 证书进行 TLS 握手。
```
其中：
```
当值为 false 时，V2Ray 只会使用操作系统自带的 CA 证书进行 TLS 握手。
```
这个地方是不是写错了，应该是：
```
当值为 false 时，允许使用操作系统自带的 CA 证书进行 TLS 握手。
```
还有默认值是不是应该改为true比较好，Nginx等Web服务，难道会用操作系统中的CA证书和客户端握手？

**Comment by kslr** [comment]
1. 只会使用系统的证书
2. 解决中间人攻击

**Comment by ghost** [comment]
> 1. 只会使用系统的证书
> 2. 解决中间人攻击

可是我设置了disableSystemRoot=false，仍然是使用certificates 中指定的证书进行 TLS 握手呀，还是说这个参数只适用于客户端？或者说我对TLS握手存在什么误解，TLS握手和建立连接使用的证书不是一个证书？

**Comment by kslr** [comment]
看过代码才能确定，不过我现在没时间，你可以先看看
