### ISSUE TITLE
Missing document for 《 Support "services" root config in cfgv4 》

### ISSUE THREAD

**Issue by xiaokangwang** [v2fly/v2fly-github-io#459]
Contribution welcome for the merged pull request without document: https://github.com/v2fly/v2ray-core/pull/3006

**Comment by arinc9** [comment]
I'm working on it.

**Comment by arinc9** [comment]
@xiaokangwang there is an issue. The "subscription" service uses the jsonv5 format for the StreamConfigObject. The transport, transportSettings, and securitySettings do not exist under StreamConfigObject on the jsonv4 format.

https://github.com/v2fly/v2ray-core/blob/cc77e90254b57e552bd745727a7bf402bae3aad9/app/subscription/specs/skeleton.go

**Comment by arinc9** [comment]
Can be closed now.

**Comment by xiaokangwang** [comment]
Thanks for your contribution!
