### ISSUE TITLE
Missing document for 《feat: add MPTCP support》

### ISSUE THREAD

**Issue by xiaokangwang** [v2fly/v2fly-github-io#461]
The document for https://github.com/v2fly/v2ray-core/pull/3109 is missing, contributions are welcomed!

**Comment by xiaokangwang** [comment]
The document for v5 config is still missing.

**Comment by arinc9** [comment]
@xiaokangwang I was not sure the MPTCP support patch included the v5 config format as well. I will submit another patch to ducment it for v5.

**Comment by arinc9** [comment]
With https://github.com/v2fly/v2fly-github-io/pull/463 merged, this issue can be closed now.

**Comment by xiaokangwang** [comment]
Yes! Thanks for the reminder and contribution.
