### ISSUE TITLE
关于 sniffing 文档的描述过于含糊

### ISSUE THREAD

**Issue by floatingrain** [v2fly/v2fly-github-io#61]
[Inbounds](https://www.v2fly.org/config/inbounds.html#inboundobject)

Inbounds 文档中关于 sniffing 的说明太笼统，并且“流量探测”的描述也不够准确。建议：

- 说明 sniffing 作用在V2ray内部产生的数据内容类型（如流量类型、协议类型、域名等）；
- 说明 sniffing 的应用场景。（如 socks 代理下根据分流等）。

**Comment by Loyalsoldier** [comment]
PR is welcomed.
