### ISSUE TITLE
关于 TLSObject 中 serverName 配置项的描述过于含糊

### ISSUE THREAD

**Issue by floatingrain** [v2fly/v2fly-github-io#62]
> 指定服务器端证书的域名，在连接由 IP 建立时有用。当目标连接由域名指定时，比如在 Socks 入站时接收到了域名，或者由 Sniffing 功能探测出了域名，这个域名会自动用于 serverName，无须手动配置。

该段描述存在以下疑点：

- “连接”和“目标连接”是指客户端与被代理的网站还是指与代理服务器的连接？

- 相应地，域名是指服务器的域名还是被代理网站的域名？

**Comment by ghost** [comment]
确实，我一开始读的时候也觉得挺误导的。我觉得应该分为服务端和客户端来描述更加有条理一些。
```
客户端：
指定用于验证服务器端证书的域名，在 address 为 IP 指定时有用。当 address 由域名指定时，这个域名会自动用于 serverName，无须手动配置。
```

**Comment by floatingrain** [comment]
另外，还应该注明，使用 quic 的时候 tlsSettings 两边都应该加上 serverName ，否则会造成 missing port 的报错并且无法正常使用。
